name: Sync to OSS

on:
  push:
    branches:
      - main # 这里可以根据您的需要更改分支名称

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'  # checkout是将文件放入当前工作区，默认情况下对git文件做浅拷贝(shadow copy)，保留git log中的时间信息，采用深拷贝(deep copy)
          path: repo
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'
      - name: npm
        run: |
          cd repo/blog
          rm -rf node_modules
          npm install
          npm install -g hexo-cli
          npm update
      - name: hexo
        run: |
          cd repo
          # 取消git对中文文件的转义，否则linux会将\xxx解读为xxx找不到对应中文文件
          git config --global core.quotepath false 
          # 从git log中读取文件修改记录，并将source中文件的修改时间用touch -d进行修复
          chmod +x run.sh
          ./run.sh
          cd blog
          hexo clean
          hexo generate
          npx gulp
      - name: Install ossutil
        run: |
          curl -L https://gosspublic.alicdn.com/ossutil/1.7.0/ossutil64 -o /usr/local/bin/ossutil
          chmod +x /usr/local/bin/ossutil
      - name: Sync files to OSS
        env:
          ACCESS_KEY_ID: ${{ secrets.ALIYUN_OSS_WEB_KEY }}
          ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_OSS_WEB_SECRET }}
          ALIYUN_OSS_ENDPOINT: ${{ secrets.ENDPOINT }}
        run: |
          # 切换到代码目录
          cd repo
          ossutil rm -rf oss://web-chensnable/  --access-key-id=$ACCESS_KEY_ID --access-key-secret=$ACCESS_KEY_SECRET --endpoint=$ALIYUN_OSS_ENDPOINT
          ossutil cp -r ./blog/public oss://web-chensnable/ --access-key-id=$ACCESS_KEY_ID --access-key-secret=$ACCESS_KEY_SECRET --endpoint=$ALIYUN_OSS_ENDPOINT

