name: Sync to OSS

on:
  push:
    branches:
      - main # 这里可以根据您的需要更改分支名称

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: repo
      - name: node
        uses: actions/setup-node@v2
        node-version: '12'
        # 执行应用打包步骤
      - name: Install dependencies and build
        run: |
          npm install
          # npm run docs:build
          npm install -g hexo-cli
          hexo clean
          hexo generate
      - name: Install ossutil
        run: |
          curl -L https://gosspublic.alicdn.com/ossutil/1.7.0/ossutil64 -o /usr/local/bin/ossutil
          chmod +x /usr/local/bin/ossutil
      - name: Sync files to OSS
        env:
          ACCESS_KEY_ID: ${{ secrets.ALIYUN_OSS_WEB_KEY }}
          ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_OSS_WEB_SECRET }}
        run: |
          # 切换到代码目录
          cd repo
          ossutil rm -rf oss://web-chensnable/  --access-key-id=$ACCESS_KEY_ID --access-key-secret=$ACCESS_KEY_SECRET --endpoint=oss-cn-hangzhou.aliyuncs.com
          ossutil cp -r ./blog/public oss://web-chensnable/ --access-key-id=$ACCESS_KEY_ID --access-key-secret=$ACCESS_KEY_SECRET --endpoint=oss-cn-hangzhou.aliyuncs.com

